### ISSUE TITLE
open image > google drive > image not loaded 

### ISSUE THREAD

**Issue by najihmld** [ValentinH/react-easy-crop#439] opened 2023-02-02 03:23 UTC
*Describe the bug**
image does not load when select image in Google drive (Android device)

**To Reproduce**
1. select image
2. explore > google drive
3. Select image google drive
4. image not loaded

**Expected behavior**
image loaded

<img width="235" alt="Screen Shot 2023-02-02 at 10 16 00" src="https://user-images.githubusercontent.com/17946519/216222848-8c639fa9-9774-494d-946c-bda7b6318f09.png">

**Comment by ValentinH** [comment] 2023-02-05 21:01
I just tried it with the [Example with image selected by the user (+ auto-rotation for phone pictures)](https://codesandbox.io/s/y09komm059) listed on the Readme and indeed, it fails.
After investigating a bit, it turns out that the issue comes from the [get-orientation](https://www.npmjs.com/package/get-orientation) package. If we remove it, it works fine. See this example:
https://codesandbox.io/s/react-easy-crop-custom-image-demo-forked-zbc6rb

`get-orientation` doesn't seem to be maintained anymore so I'm not sure how to fix this.

For the moment, I added a try...catch on the original example so that it works on Gdrive even if orientation detection fails.

Please let me know if you manage to reproduce the issue without using `get-orientation`. For now, I'm closing this issue.

**Closed as completed by ValentinH** 2023-02-05 21:01 UTC
