### ISSUE TITLE
Generating background image with random colors

### ISSUE THREAD

**Issue by yusufkaraasln** [ValentinH/react-easy-crop#455] opened 2023-04-12 08:46 UTC
**Describe the bug**
 There is no issue with the first crop, but in subsequent crops, even though the areas outside the original photo are white, the background becomes a composition of colors from the previous photo, indicating that the canvas is not being cleared and it's being overwritten. Please help me 

**Images**
 
(first cropped image => success)
![image](https://user-images.githubusercontent.com/68450622/231403345-139174e4-db23-41d7-9891-71be331e77b2.png)
(second cropped image => half success)
![image](https://user-images.githubusercontent.com/68450622/231403511-e83b04f4-8549-42b0-942f-95c8f6ac2c32.png)
(last cropper image => cropped success but background failed :D)
![image](https://user-images.githubusercontent.com/68450622/231403686-09fc6eef-3357-478a-bb43-3c6db86d41fa.png)

I really never understood that please help me

**Comment by ValentinH** [comment] 2023-04-12 17:59
That's a funny effect 😁

Without seeing any code I'm not able to guess what was wrong. Ideally, please provide a codesandbox showing the issue.

**Comment by yusufkaraasln** [comment] 2023-04-13 08:30
Hahahah in a way yeah :D 

Since it is a private project, I can't upload sandbox, but I can share the relevant codes for you.


#### CropModal.jsx
```
import React from 'react';
import { Button, Modal } from 'react-bootstrap';
import Cropper from 'react-easy-crop';
import XMarkButton from './XMarkButton';
function CropModal({
  crop,
  zoom,
  setCrop,
  setZoom,
  onCropComplete,
  show,
  setShow,
  onHide,
  img,
  showCroppedImage,
  activeType,
  handleImageUpload
}) {
  // const [range, setRange] = React.useState(1)

  return (
    <Modal
      show={show}
      onHide={() => setShow(false)}
      size="lg"
      aria-labelledby="contained-modal-title-vcenter"
      centered>
      <Modal.Header>
        <Button
          onClick={() => {
            onHide();
            showCroppedImage();
            handleImageUpload(activeType);
          }}>
          Kaydet
        </Button>
        <Button
          variant="link"
          onClick={() => {
            onHide();
          }}>
          <XMarkButton />
        </Button>
      </Modal.Header>

      <Modal.Body
        className="d-flex justify-content-center"
        style={{
          height: '500px'
        }}>
        <div
          style={{
            backgroundColor: '#fff'
          }}>
          <Cropper
            image={img}
            minZoom={0.4}
            // zoom out
            // zoom in

            restrictPosition={false}
            style={{ containerStyle: { background: '#fff' } }}
            showGrid={false}
            cropShape={activeType === 'logo' ? 'rect' : 'round'}
            crop={crop}
            zoom={zoom}
            aspect={activeType === 'logo' ? 1.5 : 1}
            onCropChange={setCrop}
            onCropComplete={onCropComplete}
            onZoomChange={setZoom}
          />
        </div>
      </Modal.Body>
      <Modal.Footer className="d-flex justify-content-center">
        <input
          type="range"
          name=""
          className="w-50"
          value={zoom}
          // defaultValue={range}
          onChange={(e) => setZoom(e.target.value)}
          min={0}
          max={6}
          step={0.0001}
          id=""
        />
      </Modal.Footer>
    </Modal>
  );
}

export default CropModal;

```

#### Canvas Utils (Functions)

```
export const createImage = (url) =>
  new Promise((resolve, reject) => {
    const image = new Image();
    image.addEventListener('load', () => resolve(image));
    image.addEventListener('error', (error) => reject(error));
    image.setAttribute('crossOrigin', 'anonymous');
    image.src = url;
  });

export function getRadianAngle(degreeValue) {
  return (degreeValue * Math.PI) / 180;
}

export function rotateSize(width, height, rotation) {
  const rotRad = getRadianAngle(rotation);

  return {
    width: Math.abs(Math.cos(rotRad) * width) + Math.abs(Math.sin(rotRad) * height),
    height: Math.abs(Math.sin(rotRad) * width) + Math.abs(Math.cos(rotRad) * height)
  };
}

export default async function getCroppedImg(
  imageSrc,
  pixelCrop,
  rotation = 0,
  flip = { horizontal: false, vertical: false }
) {
  const image = await createImage(imageSrc);
  const canvas = document.createElement('canvas');
  const ctx = canvas.getContext('2d');

  if (!ctx) return null;

  const rotRad = getRadianAngle(rotation);

  const { width: bBoxWidth, height: bBoxHeight } = rotateSize(image.width, image.height, rotation);

  canvas.width = bBoxWidth;
  canvas.height = bBoxHeight;

  ctx.translate(bBoxWidth / 2, bBoxHeight / 2);
  ctx.rotate(rotRad);
  ctx.scale(flip.horizontal ? -1 : 1, flip.vertical ? -1 : 1);
  ctx.translate(-image.width / 2, -image.height / 2);

  ctx.drawImage(image, 0, 0);

  const data = ctx.getImageData(pixelCrop.x, pixelCrop.y, pixelCrop.width, pixelCrop.height);

  canvas.width = pixelCrop.width;
  canvas.height = pixelCrop.height;

  ctx.putImageData(data, 0, 0);

  const buffer = canvas.toDataURL();
  const mb = buffer.length / 1e6;

  if (mb > 10) return { error: 'Resim 10MB büyük olmamalı!' };

  return { data: buffer };
}
```

#### Cropper States 

```
  const [logo, setLogo] = React.useState();
  const [profileImage, setProfileImage] = React.useState();

  const [photoChecked, setPhotoChecked] = React.useState(false);

  const [crop, setCrop] = useState({ x: 0, y: 0 });
  const [zoom, setZoom] = useState(profile?.photo ? 1 : 1.5);

  const [croppedImg, setCroppedImg] = useState({
    profile: null,
    logo: null
  });

  const [activeType, setActiveType] = useState('photo');

  const [croppedAreaPixels, setCroppedAreaPixels] = useState(null);
  const onCropComplete = useCallback((croppedArea, croppedAreaPixels) => {
    setCroppedAreaPixels(croppedAreaPixels);
  }, []);

  const showCroppedImage = useCallback(async () => {
    try {
      const croppedImage = await getCroppedImg(
        activeType == 'photo' ? profileImage : logo,
        croppedAreaPixels
      );

      if (activeType == 'photo') {
        setCroppedImg({
          ...croppedImg,
          profile: croppedImage
        });

        formik.setFieldValue('photo', '');
        formik.setFieldValue('photo', croppedImage.data);
      } else if (activeType == 'logo') {
        setCroppedImg({
          ...croppedImg,
          logo: croppedImage
        });
        formik.setFieldValue('logo', '');
        formik.setFieldValue('logo', croppedImage.data);
      }
      handleImageUpload({ type: activeType, data: croppedImage.data });
    } catch (e) {
      console.error(e);
    }
  }, [croppedAreaPixels]);

```

**Comment by joaquin2021** [comment] 2023-05-08 14:16
@ValentinH  Hi, this issue only appear in Windows with Chrome, i cant reproduce because I use Ubuntu.
But is changing the image with different sizes in freely move and zooming.

**Comment by ValentinH** [comment] 2023-05-27 05:15
Closing as there was no answer for a while. Comment to re-open but with a codesandbox showing the issue 😉

**Closed as completed** 2023-05-27 05:15 UTC
